[[headers]]
  for = "*.js" # js files should be set this way
  [headers.values]
    Cache-Control = "public, max-age=31449600, immutable"
[[headers]]
  for = "*.css" # css files too
  [headers.values]
    Cache-Control = "public, max-age=31449600, immutable"
[[headers]]
  for = "*.woff2" # fonts too
  [headers.values]
    Cache-Control = "public, max-age=31449600, immutable"
[[headers]]
  for = "/" # hobo offline
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "/bar-back" # hobo offline
  [headers.values]
    Cache-Control = "public, max-age=300"
[[headers]]
  for = "*.json" # more hobo offline
  [headers.values]
    Cache-Control = "public, max-age=300"