const CATEGORIES = [
  'Agave (Mezcal)',
  'Agave (Tequila Blanco)',
  'Amaro (Campari)',
  'Bitters (Aromatic)',
  'Bitters (Creole)',
  'Bitters (Orange)',
  'Cream (Heavy)',
  'Egg',
  'Extract (Vanilla)',
  'Fruit (Cherry)',
  'Fruit (Lime)',
  'Fruit (Orange)',
  'Gin (American)',
  'Gin (London Dry)',
  'Juice (Lemon)',
  'Juice (Lime)',
  'Juice (Pineapple)',
  'Leaf (Mint)',
  'Liqueur (Almond)',
  'Liqueur (Falernum)',
  'Liqueur (Orange Blue)',
  'Liqueur (Orange)',
  'Milk (Sweetened Condensed)',
  'Milk (Whole)',
  'Mint',
  'Rum (Black Blended Overproof)',
  'Rum (Black Blended)',
  'Rum (Blended Aged)',
  'Rum (Blended Lightly Aged)',
  'Rum (Cane AOC Martinique Rhum Agricole Blanc)',
  'Rum (Column Still Aged)',
  'Rum (Column Still Lightly Aged)',
  'Rum (Demerara Overproof)',
  'Rum (Demerara)',
  'Rum (Pot Still Lightly Aged) (Overproof)',
  'Soda',
  'Spice (Ginger)',
  'Syrup (Agave Nectar)',
  'Syrup (Agave)',
  'Syrup (Demerara)',
  'Syrup (Grenadine)',
  'Syrup (Honey)',
  'Syrup (Mai Tai Rich Simple)',
  'Syrup (Maple)',
  'Syrup (Orgeat)',
  'Syrup (Passion Fruit)',
  'Syrup (Rich Simple)',
  'Syrup (Simple)',
  'Vermouth (Blanc)',
  'Vermouth (Dry)',
  'Vermouth (Sweet)',
  'Whiskey (Bourbon)',
  'Whiskey (Japanese)',
  'Whiskey (Rye)',
  'Wine (Red)',
];

export default () => CATEGORIES;
